# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget Push

on:
  push:
    tags:
        - 'v*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  publish:
    runs-on: ubuntu-latest
    needs: build_and_test # 表示发布作业需要在构建作业之后运行
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build and Pack
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release
    - name: Add private GitHub registry to NuGet
      run: |
        dotnet nuget add source  --username aa89227 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/aa89227/index.json"
    - name: Push generated package to GitHub registry and NuGet
      run: |
        dotnet nuget push "./SignalR.E2ETesting/bin/Release/*.nupkg" --source "github"