# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget Push

on:
  push:
    tags:
        - 'v*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  publish:
    runs-on: ubuntu-latest
    needs: build_and_test # 表示发布作业需要在构建作业之后运行
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion
    - name: Set tag to version  
      run: |
          cd ./SignalR.E2ETesting
          dotnet TagToVersion -t ${{ github.ref }}

    - name: Build and Pack
      run: |
        cd ./SignalR.E2ETesting
        dotnet build --configuration Release
        dotnet pack --configuration Release
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Add private GitHub registry to NuGet
      run: |
        nuget sources add -name github -Source https://nuget.pkg.github.com/aa89227/index.json -Username aa89227 -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Push generated package to GitHub registry and NuGet
      run: |
        cd ./SignalR.E2ETesting
        nuget push "./bin/Release/*.nupkg" -Source github -SkipDuplicate